Test: Build test

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -26,14 +26,15 @@ pipeline {
                 script{
                     sh '''
                         pwd
-                        echo DB_DOMAIN=$DB_DOMAIN > .env
-                        echo DB_PORT=$DB_PORT >> .env
+                        echo DB_DOMAIN=$DB_DOMAIN > .env || echo "Failed to create .env"
+                        echo DB_PORT=$DB_PORT >> .env || echo "Failed to append DB_PORT
                         echo DB_PORT_FASTAPI=$DB_PORT_FASTAPI >> .env
                         echo DB_NAME=$DB_NAME >> .env
                         echo DB_USERNAME=$DB_USERNAME >> .env
                         echo DB_PASSWORD=$DB_PASSWORD >> .env
 
                         ls /var/jenkins_home/workspace/J11B109_pipeline
+                        find /var/jenkins_home/workspace/J11B09_pipeline -name ".env"
                     '''
                 }
             }
