Test: Build test

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -27,7 +27,7 @@ pipeline {
                     sh '''
                         pwd
                         echo DB_DOMAIN=$DB_DOMAIN > .env || echo "Failed to create .env"
-                        echo DB_PORT=$DB_PORT >> .env || echo "Failed to append DB_PORT
+                        echo DB_PORT=$DB_PORT >> .env || echo "Failed to append DB_PORT"
                         echo DB_PORT_FASTAPI=$DB_PORT_FASTAPI >> .env
                         echo DB_NAME=$DB_NAME >> .env
                         echo DB_USERNAME=$DB_USERNAME >> .env
