Test: build test

diff --git a/backend/spring/dockerfile b/backend/spring/dockerfile
--- a/backend/spring/dockerfile
+++ b/backend/spring/dockerfile
@@ -14,7 +14,7 @@ COPY src/ src/
 # 지금 -x test로 테스트 건너뛰게 되있는데, 나중에 수정해야함
 RUN ./gradlew clean build -Pspring.profiles.active=test --no-daemon -x test
 
-RUN ls build/libs/here-law.jar || (echo "JAR file not found!!" && exit 1)
+# RUN ls build/libs/here-law.jar || (echo "JAR file not found!!" && exit 1)
 
 CMD ["java", "-jar", "build/libs/here-law.jar"]
 
